standalone_tags:
  -
    id: 0
    size: 0.0233
    name: square1_yellow
  -
    id: 1
    size: 0.0233
    name: square1_blue
  -
    id: 2
    size: 0.0233
    name: square1_orange
  -
    id: 3
    size: 0.0233
    name: square1_red
  -
    id: 4
    size: 0.0233
    name: square1_green
  -
    id: 5
    size: 0.0233
    name: square1_purple
  -
    id: 6
    size: 0.0233
    name: square1_white
  -
    id: 7
    size: 0.0233
    name: triangle1_blue
  -
    id: 8
    size: 0.0233
    name: triagnle1_yellow
  -
    id: 9
    size: 0.0233
    name: triangle1_orange
  -
    id: 10
    size: 0.0233
    name: triangle1_red
  -
    id: 11
    size: 0.0233
    name: triangle1_green
  -
    id: 12
    size: 0.0233
    name: square1_puple
  -
    id: 13
    size: 0.0233
    name: triangle2_blue
  -
    id: 14
    size: 0.0233
    name: triagnle2_yellow
  -
    id: 15
    size: 0.0233
    name: triangle2_orange
  -
    id: 16
    size: 0.0233
    name: triangle2_red
  -
    id: 17
    size: 0.0233
    name: triangle2_green
  -
    id: 18
    size: 0.0233
    name: square2_purple
  -
    id: 19
    size: 0.0233
    name: triangle2_blue
  -
    id: 20
    size: 0.0233
    name: triangle2_red
  -
    id: 21
    size: 0.0233
    name: triangle2_green
  -
    id: 22
    size: 0.0233
    name: square2_purple
  -
    id: 35
    size: 0.0233
    name: target
  -  
    id: 99
    size: 0.0233
    name: start
  - {id: 100, size: 0.06, name: tag_100}
  - {id: 101, size: 0.06, name: tag_101}
  - {id: 102, size: 0.06, name: tag_102}
  - {id: 103, size: 0.06, name: tag_103}
  - {id: 104, size: 0.06, name: tag_104}
  - {id: 105, size: 0.06, name: tag_105}
  - {id: 106, size: 0.06, name: tag_106}
  - {id: 107, size: 0.06, name: tag_107}
  - {id: 108, size: 0.06, name: tag_108}
  - {id: 109, size: 0.06, name: tag_109}
  - {id: 110, size: 0.06, name: tag_110}
  - {id: 111, size: 0.06, name: tag_111}
  - {id: 112, size: 0.06, name: tag_112}
  - {id: 113, size: 0.06, name: tag_113}
  - {id: 114, size: 0.06, name: tag_114}

